// src/App.tsx
import React, { useState, useEffect } from 'react';
import { Navbar, NavTab } from './components/Navbar';
import { HomeView } from './views/HomeView';
import { VoiceGeneratorView } from './views/VoiceGeneratorView';
import { ResultsView } from './views/ResultsView';
import { BenchmarkView } from './views/BenchmarkView';
import { CodeSwitchView } from './views/CodeSwitchView';
import { MethodologyView } from './views/MethodologyView';
import { ImpactView } from './views/ImpactView';
import { EthicsView } from './views/EthicsView';
import { SavedResultItem, ProviderCapability } from './types';
import { Heart, Volume2, ShieldCheck } from 'lucide-react';

export default function App() {
  const [activeTab, setActiveTab] = useState<NavTab>('home');
  const [savedResults, setSavedResults] = useState<SavedResultItem[]>(() => {
    try {
      const stored = localStorage.getItem('afrivoice_saved_results');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  });

  const [providers, setProviders] = useState<Record<string, ProviderCapability>>({
    sahara: {
      provider: 'sahara',
      displayName: 'Intron Sahara',
      isConfigured: false,
      supportedLanguages: ['ha', 'yo', 'ig', 'en'],
      supportsStreaming: false,
      supportsEmotion: true,
      requiresApiKey: true,
    },
    gemini: {
      provider: 'gemini',
      displayName: 'Google Gemini 3.1 Flash Voice',
      isConfigured: true,
      supportedLanguages: ['en', 'fr', 'zh', 'hi', 'es', 'ha', 'yo', 'ig'],
      supportsStreaming: true,
      supportsEmotion: true,
      requiresApiKey: true,
    },
    browser: {
      provider: 'browser',
      displayName: 'Device Native Web Speech',
      isConfigured: true,
      supportedLanguages: ['en', 'fr', 'zh', 'hi', 'es', 'ha', 'yo', 'ig'],
      supportsStreaming: false,
      supportsEmotion: false,
      requiresApiKey: false,
    },
  });

  // Fetch live provider capability status from backend
  const fetchProviders = async () => {
    try {
      const res = await fetch('/api/providers');
      const data = await res.json();
      if (data.success && data.providers) {
        setProviders(data.providers);
      }
    } catch (err) {
      console.warn('Could not fetch server provider status; using client defaults', err);
    }
  };

  useEffect(() => {
    fetchProviders();
  }, []);

  // Sync saved results to localStorage
  useEffect(() => {
    try {
      localStorage.setItem('afrivoice_saved_results', JSON.stringify(savedResults));
    } catch (e) {
      console.error('LocalStorage write error', e);
    }
  }, [savedResults]);

  const handleSaveToLibrary = (item: SavedResultItem) => {
    setSavedResults((prev) => [item, ...prev.filter((p) => p.id !== item.id)]);
  };

  const handleDeleteResult = (id: string) => {
    setSavedResults((prev) => prev.filter((item) => item.id !== id));
  };

  const handleClearAllResults = () => {
    if (window.confirm('Are you sure you want to clear your saved audio recordings?')) {
      setSavedResults([]);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 flex flex-col font-sans">
      {/* Top Navbar */}
      <Navbar
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        resultCount={savedResults.length}
        providerStatus={{
          saharaConfigured: Boolean(providers.sahara?.isConfigured),
          geminiConfigured: Boolean(providers.gemini?.isConfigured),
        }}
      />

      {/* Main View Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6">
        {activeTab === 'home' && (
          <HomeView
            onNavigate={setActiveTab}
            providerStatus={{
              saharaConfigured: Boolean(providers.sahara?.isConfigured),
              geminiConfigured: Boolean(providers.gemini?.isConfigured),
            }}
          />
        )}

        {activeTab === 'generator' && (
          <VoiceGeneratorView
            onSaveToLibrary={handleSaveToLibrary}
            savedResults={savedResults}
            providers={providers}
            onRefreshProviders={fetchProviders}
          />
        )}

        {activeTab === 'results' && (
          <ResultsView
            results={savedResults}
            onDeleteResult={handleDeleteResult}
            onClearAll={handleClearAllResults}
            onNavigate={setActiveTab}
          />
        )}

        {activeTab === 'benchmark' && <BenchmarkView />}

        {activeTab === 'codeswitch' && <CodeSwitchView />}

        {activeTab === 'methodology' && <MethodologyView />}

        {activeTab === 'impact' && <ImpactView />}

        {activeTab === 'ethics' && <EthicsView />}
      </main>

      {/* Basic Clean Footer */}
      <footer className="bg-white border-t border-slate-200 py-8 mt-12 text-slate-600 text-xs">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-4">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded bg-emerald-700 flex items-center justify-center text-white">
                <Volume2 className="w-4 h-4" />
              </div>
              <div>
                <span className="font-semibold text-slate-900 text-sm">AfriVoice Studio</span>
                <span className="text-slate-400 mx-2">|</span>
                <span className="text-slate-500 text-xs">
                  Multilingual Voice & Speech Evaluation Tool
                </span>
              </div>
            </div>

            <div className="flex flex-wrap items-center justify-center gap-4 text-xs text-slate-600">
              <button onClick={() => setActiveTab('home')} className="hover:text-slate-900 transition-colors">
                Home
              </button>
              <button onClick={() => setActiveTab('generator')} className="hover:text-slate-900 transition-colors">
                Voice Generator
              </button>
              <button onClick={() => setActiveTab('benchmark')} className="hover:text-slate-900 transition-colors">
                Benchmark
              </button>
              <button onClick={() => setActiveTab('codeswitch')} className="hover:text-slate-900 transition-colors">
                Code-Switching
              </button>
              <button onClick={() => setActiveTab('methodology')} className="hover:text-slate-900 transition-colors">
                Methodology
              </button>
              <button onClick={() => setActiveTab('impact')} className="hover:text-slate-900 transition-colors">
                Healthcare Impact
              </button>
              <button onClick={() => setActiveTab('ethics')} className="hover:text-slate-900 transition-colors">
                Ethics & Safety
              </button>
            </div>
          </div>

          <div className="pt-3 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-2 text-[11px] text-slate-500">
            <div className="flex items-center gap-1.5">
              <ShieldCheck className="w-3.5 h-3.5 text-slate-400" />
              <span>
                Public health communication & empirical evaluation utility. De-identified clinical audio.
              </span>
            </div>
            <div>Hausa · Igbo · Yoruba · Nigerian English · French · Spanish · Chinese · Hindi</div>
          </div>
        </div>
      </footer>
    </div>
  );
}

// src/App.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';
import Navbar from './components/Navbar.vue';
import type { NavTab } from './components/navTabs';
import HomeView from './views/HomeView.vue';
import VoiceGeneratorView from './views/VoiceGeneratorView.vue';
import ResultsView from './views/ResultsView.vue';
import BenchmarkView from './views/BenchmarkView.vue';
import CodeSwitchView from './views/CodeSwitchView.vue';
import MethodologyView from './views/MethodologyView.vue';
import ImpactView from './views/ImpactView.vue';
import EthicsView from './views/EthicsView.vue';
import AppErrorBoundary from './components/AppErrorBoundary.vue';
import DiagnosticsPanel from './components/DiagnosticsPanel.vue';
import { Volume2, ShieldCheck } from 'lucide-vue-next';
import type { SavedResultItem, ProviderCapability } from './types';
import { PROVIDER_CAPABILITIES } from './services/tts/voices';
import { logError } from './utils/diagnostics';

const activeTab = ref<NavTab>('home');

function loadSavedResults(): SavedResultItem[] {
  try {
    const stored = localStorage.getItem('afrivoice_saved_results');
    return stored ? JSON.parse(stored) : [];
  } catch (err) {
    logError('localStorage:read', err);
    return [];
  }
}

const savedResults = ref<SavedResultItem[]>(loadSavedResults());
const storageWarning = ref<string | null>(null);

// Seed provider state from the real capability definitions (correct shape),
// then refresh isConfigured/statusMessage live from the server below. The
// previous implementation replaced this whole object with a hand-rolled
// literal that didn't satisfy ProviderCapability and broke the build.
const providers = ref<Record<string, ProviderCapability>>(
  JSON.parse(JSON.stringify(PROVIDER_CAPABILITIES))
);

async function fetchProviders() {
  try {
    const res = await fetch('/api/providers/status');
    if (!res.ok) return;
    const data = await res.json();
    if (!data.providers) return;

    for (const key of Object.keys(providers.value)) {
      const live = data.providers[key];
      if (live) {
        providers.value[key] = {
          ...providers.value[key],
          isConfigured: Boolean(live.isConfigured),
          statusMessage: live.statusMessage ?? providers.value[key].statusMessage,
        };
      }
    }
  } catch (err) {
    console.warn('Could not fetch server provider status; using client defaults', err);
  }
}

onMounted(fetchProviders);

watch(
  savedResults,
  (results) => {
    try {
      localStorage.setItem('afrivoice_saved_results', JSON.stringify(results));
      storageWarning.value = null;
    } catch (err) {
      logError('localStorage:write', err);
      storageWarning.value =
        'Your browser storage is full, so the newest recording may not have been saved for next time. Try clearing some items from My Results.';
    }
  },
  { deep: true }
);

function handleSaveToLibrary(item: SavedResultItem) {
  savedResults.value = [item, ...savedResults.value.filter((p) => p.id !== item.id)];
}

function handleDeleteResult(id: string) {
  savedResults.value = savedResults.value.filter((item) => item.id !== id);
}

function handleClearAllResults() {
  if (window.confirm('Are you sure you want to clear your saved audio recordings?')) {
    savedResults.value = [];
  }
}

function providerStatus() {
  return {
    saharaConfigured: Boolean(providers.value.sahara?.isConfigured),
    geminiConfigured: Boolean(providers.value.gemini?.isConfigured),
  };
}
</script>

<template>
  <div class="min-h-screen bg-slate-50 text-slate-800 flex flex-col font-sans">
    <Navbar
      :active-tab="activeTab"
      :result-count="savedResults.length"
      :provider-status="providerStatus()"
      @select="(tab) => (activeTab = tab)"
    />

    <main class="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6">
      <div v-if="storageWarning" class="mb-4 p-3 rounded-lg bg-amber-50 border border-amber-200 text-xs text-amber-900">
        {{ storageWarning }}
      </div>

      <!-- :key forces the boundary (and its hasError state) to reset whenever
           the user switches tabs, matching the fallback UI's own "switch to
           a different tab" recovery instruction. -->
      <AppErrorBoundary :key="activeTab">
        <HomeView v-if="activeTab === 'home'" @navigate="(tab) => (activeTab = tab)" />

        <VoiceGeneratorView
          v-else-if="activeTab === 'generator'"
          :saved-results="savedResults"
          :providers="providers"
          @save-to-library="handleSaveToLibrary"
        />

        <ResultsView
          v-else-if="activeTab === 'results'"
          :results="savedResults"
          @delete-result="handleDeleteResult"
          @clear-all="handleClearAllResults"
          @navigate="(tab) => (activeTab = tab)"
        />

        <BenchmarkView v-else-if="activeTab === 'benchmark'" />
        <CodeSwitchView v-else-if="activeTab === 'codeswitch'" />
        <MethodologyView v-else-if="activeTab === 'methodology'" />
        <ImpactView v-else-if="activeTab === 'impact'" />
        <EthicsView v-else-if="activeTab === 'ethics'" />
      </AppErrorBoundary>
    </main>

    <footer class="bg-white border-t border-slate-200 py-8 mt-12 text-slate-600 text-xs">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-4">
        <div class="flex flex-col md:flex-row items-center justify-between gap-4">
          <div class="flex items-center gap-2.5">
            <div class="w-7 h-7 rounded bg-emerald-700 flex items-center justify-center text-white">
              <Volume2 class="w-4 h-4" />
            </div>
            <div>
              <span class="font-semibold text-slate-900 text-sm">AfriVoice Studio</span>
              <span class="text-slate-400 mx-2">|</span>
              <span class="text-slate-500 text-xs">Multilingual Voice & Speech Evaluation Tool</span>
            </div>
          </div>

          <div class="flex flex-wrap items-center justify-center gap-4 text-xs text-slate-600">
            <button class="hover:text-slate-900 transition-colors" @click="activeTab = 'home'">Home</button>
            <button class="hover:text-slate-900 transition-colors" @click="activeTab = 'generator'">Voice Generator</button>
            <button class="hover:text-slate-900 transition-colors" @click="activeTab = 'benchmark'">Benchmark</button>
            <button class="hover:text-slate-900 transition-colors" @click="activeTab = 'codeswitch'">Code-Switching</button>
            <button class="hover:text-slate-900 transition-colors" @click="activeTab = 'methodology'">Methodology</button>
            <button class="hover:text-slate-900 transition-colors" @click="activeTab = 'impact'">Healthcare Impact</button>
            <button class="hover:text-slate-900 transition-colors" @click="activeTab = 'ethics'">Ethics & Safety</button>
          </div>
        </div>

        <div class="pt-3 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-2 text-[11px] text-slate-500">
          <div class="flex items-center gap-1.5">
            <ShieldCheck class="w-3.5 h-3.5 text-slate-400" />
            <span>Public health communication & empirical evaluation utility. De-identified clinical audio.</span>
          </div>
          <div>Hausa · Igbo · Yoruba · Nigerian English · French · Spanish · Chinese · Hindi</div>
        </div>
      </div>
    </footer>

    <DiagnosticsPanel />
  </div>
</template>
